
--------- VALIDATE PHONE NUMBERS PROCEDURES ----------------

DROP PROCEDURE IF EXISTS validate_mobile;
DELIMITER $$
CREATE PROCEDURE validate_mobile(
	IN mobile VARCHAR(128)
)
DETERMINISTIC
NO SQL
BEGIN
	IF NOT (SELECT mobile REGEXP '^[0-9]{8,30}$') THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Wrong mobile';
	END IF;
END$$
DELIMITER ;